### ISSUE TITLE
Prepreke

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG48-cross-the-road#3]
Trenutno su prepreke ogroman kvadar. Napraviti kompleksniji model prepreke. Dodatno se mogu ubaciti vise vrsta prepreki.

**Comment by andjaam** [comment]
Dodata je jos jedna vrsta prepreka.

**Comment by andjaam** [comment]
Stare prepreke su skroz zamenjene novim.
